/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as DashboardRouteImport } from './pages/Dashboard'
import { Route as MyProfileRouteImport } from './pages/MyProfile'
import { Route as PostingArchiveRouteImport } from './pages/PostingArchive'
import { Route as ApplicationsIndexRouteImport } from './pages/Applications.index'
import { Route as ApplicationsApplicationIdRouteImport } from './pages/Applications.$applicationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/MyProfile',
  path: '/MyProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostingArchiveRoute = PostingArchiveRouteImport.update({
  id: '/PostingArchive',
  path: '/PostingArchive',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsIndexRoute = ApplicationsIndexRouteImport.update({
  id: '/Applications/',
  path: '/Applications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsApplicationIdRoute =
  ApplicationsApplicationIdRouteImport.update({
    id: '/Applications/$applicationId',
    path: '/Applications/$applicationId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/MyProfile': typeof MyProfileRoute
  '/PostingArchive': typeof PostingArchiveRoute
  '/Applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/Applications/': typeof ApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/MyProfile': typeof MyProfileRoute
  '/PostingArchive': typeof PostingArchiveRoute
  '/Applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/Applications': typeof ApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Dashboard': typeof DashboardRoute
  '/MyProfile': typeof MyProfileRoute
  '/PostingArchive': typeof PostingArchiveRoute
  '/Applications/$applicationId': typeof ApplicationsApplicationIdRoute
  '/Applications/': typeof ApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/Dashboard'
    | '/MyProfile'
    | '/PostingArchive'
    | '/Applications/$applicationId'
    | '/Applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/Dashboard'
    | '/MyProfile'
    | '/PostingArchive'
    | '/Applications/$applicationId'
    | '/Applications'
  id:
    | '__root__'
    | '/'
    | '/Dashboard'
    | '/MyProfile'
    | '/PostingArchive'
    | '/Applications/$applicationId'
    | '/Applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardRoute: typeof DashboardRoute
  MyProfileRoute: typeof MyProfileRoute
  PostingArchiveRoute: typeof PostingArchiveRoute
  ApplicationsApplicationIdRoute: typeof ApplicationsApplicationIdRoute
  ApplicationsIndexRoute: typeof ApplicationsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MyProfile': {
      id: '/MyProfile'
      path: '/MyProfile'
      fullPath: '/MyProfile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PostingArchive': {
      id: '/PostingArchive'
      path: '/PostingArchive'
      fullPath: '/PostingArchive'
      preLoaderRoute: typeof PostingArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Applications/': {
      id: '/Applications/'
      path: '/Applications'
      fullPath: '/Applications/'
      preLoaderRoute: typeof ApplicationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Applications/$applicationId': {
      id: '/Applications/$applicationId'
      path: '/Applications/$applicationId'
      fullPath: '/Applications/$applicationId'
      preLoaderRoute: typeof ApplicationsApplicationIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardRoute: DashboardRoute,
  MyProfileRoute: MyProfileRoute,
  PostingArchiveRoute: PostingArchiveRoute,
  ApplicationsApplicationIdRoute: ApplicationsApplicationIdRoute,
  ApplicationsIndexRoute: ApplicationsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
