/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './pages/__root'
import { Route as IndexRouteImport } from './pages/index'
import { Route as ApplicationsRouteImport } from './pages/Applications'
import { Route as DashboardRouteImport } from './pages/Dashboard'
import { Route as MyProfileRouteImport } from './pages/MyProfile'
import { Route as PostingArchiveRouteImport } from './pages/PostingArchive'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplicationsRoute = ApplicationsRouteImport.update({
  id: '/Applications',
  path: '/Applications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/Dashboard',
  path: '/Dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MyProfileRoute = MyProfileRouteImport.update({
  id: '/MyProfile',
  path: '/MyProfile',
  getParentRoute: () => rootRouteImport,
} as any)
const PostingArchiveRoute = PostingArchiveRouteImport.update({
  id: '/PostingArchive',
  path: '/PostingArchive',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/Applications': typeof ApplicationsRoute
  '/Dashboard': typeof DashboardRoute
  '/MyProfile': typeof MyProfileRoute
  '/PostingArchive': typeof PostingArchiveRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/Applications': typeof ApplicationsRoute
  '/Dashboard': typeof DashboardRoute
  '/MyProfile': typeof MyProfileRoute
  '/PostingArchive': typeof PostingArchiveRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/Applications': typeof ApplicationsRoute
  '/Dashboard': typeof DashboardRoute
  '/MyProfile': typeof MyProfileRoute
  '/PostingArchive': typeof PostingArchiveRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/Applications' | '/Dashboard' | '/MyProfile' | '/PostingArchive'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/Applications' | '/Dashboard' | '/MyProfile' | '/PostingArchive'
  id:
    | '__root__'
    | '/'
    | '/Applications'
    | '/Dashboard'
    | '/MyProfile'
    | '/PostingArchive'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApplicationsRoute: typeof ApplicationsRoute
  DashboardRoute: typeof DashboardRoute
  MyProfileRoute: typeof MyProfileRoute
  PostingArchiveRoute: typeof PostingArchiveRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Applications': {
      id: '/Applications'
      path: '/Applications'
      fullPath: '/Applications'
      preLoaderRoute: typeof ApplicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/Dashboard': {
      id: '/Dashboard'
      path: '/Dashboard'
      fullPath: '/Dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/MyProfile': {
      id: '/MyProfile'
      path: '/MyProfile'
      fullPath: '/MyProfile'
      preLoaderRoute: typeof MyProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/PostingArchive': {
      id: '/PostingArchive'
      path: '/PostingArchive'
      fullPath: '/PostingArchive'
      preLoaderRoute: typeof PostingArchiveRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApplicationsRoute: ApplicationsRoute,
  DashboardRoute: DashboardRoute,
  MyProfileRoute: MyProfileRoute,
  PostingArchiveRoute: PostingArchiveRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
